baseURL = '/'
languageCode = 'en-US'
title = 'Sebastien Sanz de Santamaria'
subtitle = 'Product Owner, Web Developer, Cultural Producer'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false
disableLanguages = []
disableHugoGeneratorInject = false

[params]
  logo = "https://jemmsuk.github.io/hugo-language-switcher/logo/langtest-logo-45x45px.png"

[menus]
  [[menus.main]]
    identifier = 'works'
    name = 'work'
    url = 'works/'
    weight = 10
  [[menus.main]]
    identifier = 'bio'
    name = 'bio'
    url = 'bio/'
    weight = 10
  # [[menus.main]]
  #   identifier = 'tags'
  #   name = 'tags'
  #   url  = 'tags/'
  #   weight = 40

  [[menus.main]]
    identifier = 'language'
    name = 'en'
    # pre = '{{< svg-icon "bi-translate" >}}'
    weight = 30
    [[menus.main]]
        parent = "language"
        name = 'en'
        weight = 31
    [[menus.main]]
        parent = "language"
        name = 'es'
        weight = 32
    [[menus.main]]
        parent = "language"
        name = 'fr'
        weight = 33

[languages]
  [languages.en]
    languageCode = 'en-US'
    languageName = 'en ðŸ‡ºðŸ‡¸'
    LanguageDirection = 'ltr'
    timeZone = 'America/New_York'
    title = 'Sebastien Sanz de Santamaria'
    weight = 1
    [languages.en.pagination]
        path = 'page'
    [languages.en.params]
        subtitle = 'Product Owner, Full Stack Web Developer , Cultural Producer'
  [languages.es]
    languageCode = 'es-MX'
    languageName = 'es ðŸ‡²ðŸ‡½ '
    LanguageDirection = 'ltr'
    timeZone = "America/Mexico_City"
    title = 'Sebastien Sanz de Santamaria'
    weight = 2
    [languages.es.pagination]
        path = 'pÃ¡gina'
    [languages.es.params]
        subtitle = 'Product Owner, Desarrollador Web, Productor Cultural'
    [languages.es.permalinks]
        _works = "/obras/"
        works = "/obras/:slug"
  [languages.fr]
    languageCode = 'fr-FR'
    languageName = 'fr ðŸ‡«ðŸ‡·'
    LanguageDirection = 'ltr'
    timeZone = "Europe/Paris"
    title = 'Sebastien Sanz de Santamaria'
    weight = 3
    [languages.fr.pagination]
        path = 'page'
    [languages.fr.params]
        subtitle = 'Product Owner, DÃ©veloppeur Web, Producteur Culturel'
  
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"